version: "3.8"

services:
  app:
    image: 'bitnami/symfony:1'
    container_name: symfony
    ports:
      - '8000:8000'
    volumes:
      - '.:/app/APIToDoYaiza'
    environment:
      SYMFONY_PROJECT_NAME: APIToDoYaiza
      MARIADB_HOST: mariadb
      MARIADB_PORT_NUMBER: 3306
      MARIADB_ROOT_USER: ${MYSQL_ROOT_USER}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db
      - mailcatcher

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  db:
    image: mysql
    container_name: mysqldb
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT_NUMBER: 3306
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mydb:/var/lib/mysql
      - ./mydb-script/APIToDoYaiza.sql:/docker-entrypoint-initdb.d/APIToDoYaiza.sql

volumes:
  mydb:
  mydb-script:
